name: spacyCI

on: 
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: [self-hosted]
    env:
      REGISTRY: crafted.docker.ails.ece.ntua.gr
      DEPLOY_USER: deploy
      CONTAINER_NAME: spacy-ails
      IMAGE_NAME: spacy-ails
      DEPLOY_SERVER: lego.ails.ece.ntua.gr


    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
      id: extract_branch

    - name: Set tag ref
      run: |
        echo TAG_REF=${GITHUB_SHA::8} >> $GITHUB_ENV              

    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.REGISTRY }}
        username: builder
        password: ${{ secrets.CRAFTED_DOCKER_KEY }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        build-args: |
          MINT_APP=${{ env.MINT_APP }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG_REF }}
          
        # ${{ env.REGISTRY }}/${{ env.MINT_APP }}:${{ steps.extract_branch.outputs.branch }}
     

    - name: Deploy to Server
      run: |
        echo "${{ secrets.MINT_CI_SSH_KEY }}" > /tmp/sshkey
        chmod 600 /tmp/sshkey 
        ssh -i /tmp/sshkey -o StrictHostKeyChecking=no ${DEPLOY_USER}@${DEPLOY_SERVER} "cd /etc/docker && /usr/local/bin/docker-compose pull ${CONTAINER_NAME} && /usr/local/bin/docker-compose up -d ${CONTAINER_NAME}"

